from __future__ import annotations

import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path


OWNERSHIP_MARKER = "// Generated by Codelight. Do not edit.\n"


@dataclass(frozen=True, slots=True)
class TypeScriptAdapter:
    target_path: str
    source_path: str
    factory_name: str
    command: tuple[str, ...]

    @staticmethod
    def owns(path: str) -> bool:
        if os.path.islink(path) or not os.path.isfile(path):
            return False
        try:
            with open(path, encoding="utf-8") as stream:
                return stream.readline() == OWNERSHIP_MARKER
        except OSError:
            return False

    @classmethod
    def remove_if_owned(cls, path: str) -> bool:
        if not cls.owns(path):
            return False
        os.unlink(path)
        return True

    def install(self) -> bool:
        directory = os.path.dirname(os.path.abspath(self.target_path))
        os.makedirs(directory, exist_ok=True)
        if os.path.lexists(self.target_path) and not self.owns(self.target_path):
            return False
        module_uri = Path(self.source_path).resolve().as_uri()
        source = (
            OWNERSHIP_MARKER
            + f'import {{ {self.factory_name} }} from {json.dumps(module_uri)};\n\n'
            f'export default {self.factory_name}({json.dumps(self.command)});\n'
        )
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=directory,
            prefix=".codelight-adapter.",
            delete=False,
        ) as stream:
            stream.write(source)
            temporary_path = stream.name
        try:
            os.replace(temporary_path, self.target_path)
        finally:
            if os.path.exists(temporary_path):
                os.unlink(temporary_path)
        return True
