import json
import os
import socket
import subprocess
import sys
import tempfile
import unittest


sys.path.insert(0, os.path.dirname(__file__))

from codelight_core.agents import claude
from codelight_core.agents import claude_desktop
from codelight_core.agents import codex
from codelight_core.agents import omp
from codelight_core.agents import opencode
from codelight_core.agents.typescript_adapter import TypeScriptAdapter
from codelight_core import hook_commands
from codelight_core import lifecycle


class TypeScriptAdapterOwnershipTests(unittest.TestCase):
    def adapter(self, target_path: str, command: tuple[str, ...] = ("codelight",)):
        return TypeScriptAdapter(
            target_path=target_path,
            source_path=__file__,
            factory_name="createAdapter",
            command=command,
        )

    def test_unowned_file_is_neither_overwritten_nor_removed(self):
        with tempfile.TemporaryDirectory() as tmp:
            target_path = os.path.join(tmp, "codelight.ts")
            with open(target_path, "w", encoding="utf-8") as stream:
                stream.write("export default 'user-owned';\n")

            self.assertFalse(self.adapter(target_path).install())
            self.assertFalse(TypeScriptAdapter.remove_if_owned(target_path))

            with open(target_path, encoding="utf-8") as stream:
                self.assertEqual(stream.read(), "export default 'user-owned';\n")

    def test_owned_file_can_be_updated_and_removed(self):
        with tempfile.TemporaryDirectory() as tmp:
            target_path = os.path.join(tmp, "codelight.ts")
            self.assertTrue(self.adapter(target_path).install())
            self.assertTrue(self.adapter(target_path, ("new-codelight",)).install())

            with open(target_path, encoding="utf-8") as stream:
                source = stream.read()
            self.assertTrue(source.startswith("// Generated by Codelight."))
            self.assertIn("new-codelight", source)

            self.assertTrue(TypeScriptAdapter.remove_if_owned(target_path))
            self.assertFalse(os.path.lexists(target_path))

    def test_symlink_target_is_preserved_even_when_marked(self):
        with tempfile.TemporaryDirectory() as tmp:
            owned_path = os.path.join(tmp, "owned.ts")
            target_path = os.path.join(tmp, "codelight.ts")
            self.assertTrue(self.adapter(owned_path).install())
            os.symlink(owned_path, target_path)

            self.assertFalse(self.adapter(target_path).install())
            self.assertFalse(TypeScriptAdapter.remove_if_owned(target_path))
            self.assertTrue(os.path.islink(target_path))


class OmpIntegrationTests(unittest.TestCase):
    def test_installer_writes_extension_that_invokes_this_codelight(self):
        with tempfile.TemporaryDirectory() as tmp:
            extension_path = os.path.join(tmp, "extensions", "codelight.ts")
            integration = omp.build_integration({"extension_path": extension_path})

            integration.install_hooks(
                script_path="/tmp/forked codelight.py",
                hook_wait_ceiling=590,
                remote_permissions=False,
                remote_questions=False,
                permission_timeout=60,
                log=None,
            )

            with open(extension_path, encoding="utf-8") as stream:
                wrapper = stream.read()

        self.assertIn("createOmpExtension", wrapper)
        self.assertIn('"/tmp/forked codelight.py"', wrapper)
        self.assertIsNotNone(integration.install_hooks)
        self.assertIn(extension_path, integration.removable_adapter_files)


class OpenCodePluginIntegrationTests(unittest.TestCase):
    def test_plugin_source_owns_status_when_configured(self):
        with tempfile.TemporaryDirectory() as tmp:
            plugin_path = os.path.join(tmp, "plugins", "codelight.ts")
            integration = opencode.build_integration({
                "status_source": "plugin",
                "plugin_path": plugin_path,
            })

            self.assertIsNotNone(integration.install_hooks)
            self.assertIsNone(integration.background_listener)

            integration.install_hooks(
                script_path="/tmp/codelight.py",
                hook_wait_ceiling=590,
                remote_permissions=False,
                remote_questions=False,
                permission_timeout=60,
                log=None,
            )

            with open(plugin_path, encoding="utf-8") as stream:
                wrapper = stream.read()

        self.assertIn("createOpenCodePlugin", wrapper)
        self.assertIn(plugin_path, integration.removable_adapter_files)


class ClaudeDesktopIntegrationTests(unittest.TestCase):
    def test_metadata_age_maps_to_agent_deck_lifecycle(self):
        now_ms = 2_000_000

        self.assertEqual(
            claude_desktop.status_for_metadata(
                now_ms=now_ms,
                last_activity_ms=now_ms - 99_000,
                archived=False,
            ),
            "working",
        )
        self.assertEqual(
            claude_desktop.status_for_metadata(
                now_ms=now_ms,
                last_activity_ms=now_ms - 100_000,
                archived=False,
            ),
            "waiting",
        )
        self.assertEqual(
            claude_desktop.status_for_metadata(
                now_ms=now_ms,
                last_activity_ms=now_ms - 900_000,
                archived=False,
            ),
            "idle",
        )
        self.assertEqual(
            claude_desktop.status_for_metadata(
                now_ms=now_ms,
                last_activity_ms=now_ms,
                archived=True,
            ),
            "ended",
        )

    def test_open_desktop_app_is_not_itself_coding_activity(self):
        self.assertEqual(claude_desktop.SPEC.process_executables, ())

    def test_future_activity_is_unknown(self):
        self.assertEqual(
            claude_desktop.status_for_metadata(
                now_ms=2_000_000,
                last_activity_ms=2_000_001,
                archived=False,
            ),
            "unknown",
        )

    def test_malformed_archive_marker_is_not_treated_as_archived(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "local_session.json")
            with open(path, "w", encoding="utf-8") as stream:
                json.dump(
                    {
                        "sessionId": "session-1",
                        "lastActivityAt": 1_000,
                        "isArchived": "false",
                    },
                    stream,
                )

            sessions = claude_desktop.scan_sessions(tmp)

        self.assertEqual(sessions, ())


class AgentProcessProbeTests(unittest.TestCase):
    def test_wrapper_command_token_keeps_provider_alive(self):
        probe = lifecycle.AgentProcessProbe(
            {
                "omp": ("omp",),
                "codex": ("codex",),
            },
            command_lines=lambda: (
                "/usr/bin/python3 /tmp/codelight.py --name test",
                "/opt/homebrew/bin/bun /Users/test/bin/omp --model test",
            ),
        )

        self.assertTrue(probe("omp"))
        self.assertFalse(probe("codex"))

    def test_process_listing_failure_is_unknown(self):
        probe = lifecycle.AgentProcessProbe(
            {"codex": ("codex",)},
            command_lines=lambda: None,
        )

        self.assertIsNone(probe("codex"))

    def test_unmatched_prompt_quote_does_not_hide_live_provider(self):
        probe = lifecycle.AgentProcessProbe(
            {"codex": ("codex",)},
            command_lines=lambda: (
                "/opt/homebrew/bin/codex exec explain user's request",
            ),
        )

        self.assertTrue(probe("codex"))

    def test_deep_wrapper_and_spaced_path_do_not_hide_live_providers(self):
        probe = lifecycle.AgentProcessProbe(
            {
                "omp": ("omp",),
                "codex": ("codex",),
            },
            command_lines=lambda: (
                "/usr/bin/env -S bun --smol /Users/test/bin/omp --model test",
                "'/Applications/Agent Tools/codex' exec explain user's request",
            ),
        )

        self.assertTrue(probe("omp"))
        self.assertTrue(probe("codex"))

    def test_batch_snapshot_reads_process_table_once(self):
        calls = 0

        def command_lines():
            nonlocal calls
            calls += 1
            return ("/Users/test/bin/omp",)

        probe = lifecycle.AgentProcessProbe(
            {"omp": ("omp",), "codex": ("codex",)},
            command_lines=command_lines,
        )

        states = probe.snapshot({"omp", "codex"})

        self.assertEqual(states, {"omp": True, "codex": False})
        self.assertEqual(calls, 1)

    def test_embedded_opencode_host_keeps_provider_alive(self):
        probe = lifecycle.AgentProcessProbe(
            {"opencode": opencode.SPEC.process_executables},
            command_lines=lambda: (
                "/Applications/OpenCode.app/Contents/MacOS/OpenCode",
            ),
        )

        self.assertTrue(probe("opencode"))

    def test_vibeterm_shell_does_not_count_as_opencode_runtime(self):
        probe = lifecycle.AgentProcessProbe(
            {"opencode": opencode.SPEC.process_executables},
            command_lines=lambda: (
                "/Applications/VibeTerm.app/Contents/MacOS/VibeTerm",
            ),
        )

        self.assertFalse(probe("opencode"))


class StableHookCompatibilityTests(unittest.TestCase):
    def test_stable_commands_deliver_claude_and_codex_events(self):
        script_path = os.path.join(os.path.dirname(__file__), "codelight.py")
        for provider in ("claude", "codex"):
            with self.subTest(provider=provider), tempfile.TemporaryDirectory() as tmp:
                socket_path = os.path.join(tmp, "codelight.sock")
                with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as server:
                    server.bind(socket_path)
                    server.listen(1)
                    server.settimeout(5)
                    result = subprocess.run(
                        [script_path, "hook", "--provider", provider],
                        input=json.dumps(
                            {
                                "hook_event_name": "UserPromptSubmit",
                                "session_id": f"{provider}-session",
                            }
                        ),
                        capture_output=True,
                        text=True,
                        timeout=5,
                        env={**os.environ, "CODELIGHT_CONFIG_HOME": tmp},
                    )
                    conn, _ = server.accept()
                    with conn:
                        raw = b""
                        while chunk := conn.recv(4096):
                            raw += chunk

                self.assertEqual(result.returncode, 0, result.stderr)
                payload = json.loads(raw)
                observed_at = payload.pop("observed_at")
                self.assertIsInstance(observed_at, float)
                self.assertGreater(observed_at, 0)
                order_token = payload.pop("order_token")
                authority_rank = payload.pop("authority_rank")
                operation_id = payload.pop("operation_id")
                lease_deadline_ns = payload.pop("lease_deadline_ns")
                self.assertIsInstance(order_token, int)
                self.assertEqual(authority_rank, 2)
                self.assertRegex(operation_id, r"\A[0-9a-f]{32}\Z")
                self.assertGreater(lease_deadline_ns, order_token)
                self.assertEqual(
                    payload,
                    {
                        "state": "working",
                        "session_id": f"{provider}-session",
                        "agent_id": provider,
                        "transcript_path": "",
                        "cwd": "",
                        "hook_event": "UserPromptSubmit",
                        "authority_scope": f"unresolved:{provider}",
                        "authority_generation": "",
                        "provider_evidence_complete": False,
                    },
                )

    def test_legacy_event_names_map_to_codelight_states(self):
        self.assertEqual(
            hook_commands.legacy_status_state({"hook_event_name": "Stop"}),
            "ended",
        )
        self.assertEqual(
            hook_commands.legacy_status_state(
                {"hook_event_name": "PermissionRequest"}
            ),
            "waiting",
        )
        self.assertEqual(
            hook_commands.legacy_status_state(
                {"hook_event_name": "UserPromptSubmit"}
            ),
            "working",
        )
        self.assertEqual(
            hook_commands.legacy_status_state(
                {"hook_event_name": "SessionStart"}
            ),
            "idle",
        )
        self.assertEqual(hook_commands.legacy_status_state({}), "unknown")

    def test_terminal_hook_evidence_does_not_expire(self):
        self.assertEqual(
            hook_commands.lease_deadline_ns("ended", 123),
            9_223_372_036_854_775_807,
        )
        self.assertEqual(
            hook_commands.lease_deadline_ns("working", 123),
            600_000_000_123,
        )

    def test_managed_hook_installation_can_be_disabled_per_agent(self):
        claude_integration = claude.build_integration({"manage_hooks": False})
        codex_integration = codex.build_integration({"manage_hooks": False})

        self.assertIsNone(claude_integration.install_hooks)
        self.assertEqual(claude_integration.removable_hook_paths, ())
        self.assertIsNone(codex_integration.install_hooks)
        self.assertEqual(codex_integration.removable_hook_paths, ())
